services:
  ui:
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL:-}
        GIT_COMMIT: ${GIT_COMMIT:-}
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/api/db.sqlite3

    # If your proxy is traefik add this:
    # networks:
    #   - proxy
    # labels:
    #   traefik.enable: true
    #   traefik.docker.network: proxy
    #   traefik.http.routers.qlue-ui.entrypoints: websecure
    #   traefik.http.routers.qlue-ui.rule: Host(`qlue-ls.com`)
    #   traefik.http.routers.qlue-ui.tls: true
    #   traefik.http.routers.qlue-ui.tls.certresolver: http_resolver
    #   traefik.http.routers.qlue-ui.service: qlue-ui
    #   traefik.http.services.qlue-ui.loadbalancer.server.port: 7000
# networks:
#   proxy:
#     external: true
