name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile backend/pyproject.toml
        pip install -r backend/requirements.txt
    - name: Setup DB
      working-directory: backend
      run: |
          cp ../db.sqlite3.dist db.sqlite3
          python manage.py migrate
    - name: Install node dependencies (webapp)
      working-directory: frontend
      run: npm ci
    - name: Install node dependencies (testing)
      working-directory: testing
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: testing
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: testing
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: testing/playwright-report/
        retention-days: 30
